---
version: "3"

volumes:
  data:

services:

  fexapi:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    restart: always
    depends_on:
      - "db"
    env_file:
      - '.variables.env'
    volumes:
      - ./fexapi:/fexapi
    ports:
      - "8000:8000"

  fexservice:
    build: 
      context: .
      dockerfile: ./docker/service/Dockerfile
    restart: always
    depends_on:
      - "db"
    env_file:
      - '.variables.env'
    volumes:
      - ./fexservice:/fexservice

  db:
    image: postgres:12.1
    restart: always
    env_file:
      - '.variables.env'
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
